# Generated by Django 2.0.6 on 2018-06-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='file',
            new_name='image',
        ),
    ]
