# Generated by Django 2.0.6 on 2018-06-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0002_auto_20180609_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
    ]
