# Generated by Django 2.0.6 on 2018-06-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0002_auto_20180610_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image_id',
            field=models.IntegerField(),
        ),
    ]
