# Generated by Django 2.0.6 on 2018-06-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0003_delete_uploadfilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='remark',
        ),
    ]
