# Generated by Django 2.0.6 on 2018-06-09 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0004_remove_fish_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapi.Fish')),
            ],
        ),
    ]
